databases:
  - name: hellorails
    databaseName: hellorails
    user: hellorails

services:
  - type: web
    name: hellorails
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hellorails
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false